[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceGroteskHeader"
url = "app/static/SpaceGrotesk-SemiBold.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
primaryColor = "#bb5a38"              
backgroundColor = "#e8e7dd"           
secondaryBackgroundColor = "#dad8ce"  
textColor = "#333026"                 
linkColor = "#bb5a38"                 
borderColor = "#c8c6bd"               
codeBackgroundColor = "#ecebe4"      
showWidgetBorder = true
showSidebarBorder = true
baseRadius = "0.6rem"
font = "SpaceGrotesk"
headingFont = "SpaceGroteskHeader"
codeFont = "SpaceMono"


[theme.sidebar]
backgroundColor = "#b6b4ab"            
secondaryBackgroundColor = "#dad8ce"   
textColor = "#333026"                 
linkColor = "#bb5a38"                  
